server:
  port: 8090


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eosb_error_handling_validation
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

